alg_name: "FT"
model_name: "bigscience/bloom-7b1"
device: 0

# This was put arbitrarily, interpolated roughly from ROME Llama having
# v_loss_layer 31 and Bloom having 29, then since Llama has layers = [21] for
# FT, then we put 19 here. A better choice might be out there 
layers: [19]
num_steps: 100
batch_size: 1
max_length: 40
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: false
# In our survey paper(https://arxiv.org/abs/2401.01286) 
# "prompt_last" corresponds to the results of FT-L.
# "target_new" corresponds to the results of FT-M.
objective_optimization: "prompt_last"
rewrite_module_tmp: "transformer.h.{}.mlp.dense_4h_to_h"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.self_attention"
ln_f_module: "transformer.ln_f"
lm_head_module: "lm_head"
model_parallel: false