alg_name: "ReFT"
device: "cuda"

layers: [12]
pos_type: "all_tokens"
num_steps: 100
# batch_size: 1
# max_length: 40
lr: 5e-4
low_rank_dim: 4
intervention_type: "loreft"
component: "block_output"
model_parallel: false
bf16: true