defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
timeout_min: 60 # 1 hour
partition: ${oc.env:DEFPART}
mem_gb : 300
cpus_per_task: 12
gres: gpu:1
additional_parameters: {"mail-user": "${oc.env:USER_MAIL}", "mail-type": "ALL"}
